default_roles:
  - system
  #- create_user
  - zsh
  - git
  - fonts
  - neofetch
  - starship
  - azure_cli
  - github_cli
  - kubectl
  - terraform
  
#new_user: <userName>
#new_user_password: new_user_password

git_user_email: git_user_email
git_user_name: git_user_name
