default_roles:
  -  # System packages should be installed first
    #- system
    #- create_user
    - bash
    - zsh
  -  # Install remaining roles in order  
    - tmux
    - git
    - fonts
    - neofetch
    - neovim
    - starship
    - azure_cli
    - github_cli
    - kubectl
    - terraform
    - powershell

host_user: "{{ lookup('pipe', 'whoami') }}"

# Role [create use] - valuses stored in vault.yml 
#new_user: <userName>
#new_user_password: new_user_password

# Role [git] - valuses stored in vault.yml
git_user_email: git_user_email
git_user_name: git_user_name

kubectl:
  repo_version: "v1.30"