default_roles:
  - system
  - create_user
  - zsh
  - fonts
  - neofetch
  - starship
  - azure_cli
  - github_cli
  - kubectl
  - terraform
  

new_user: jiadmin
new_user_password: new_user_password