- name: Add the GitHub CLI Repository and Install GigHub CLI
  block:
    - name: Download and set up GitHub CLI GPG key
      ansible.builtin.apt_key:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg
    - name: Add GitHub CLI repository
      ansible.builtin.apt_repository:
        repo: >
          deb 
          #[arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] 
          [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg]
          https://cli.github.com/packages 
          stable 
          main
    - name: Install GitHub CLI
      apt:
        name: gh
        state: latest
        update_cache: true
  become: true    