---
- hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true    

    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - wget
          - tree
          - zsh
        state: latest
        update_cache: true

#    - name: Remove package (if installed)
#      apt:
#        pkg:
#          - nvim
#        state: absent  # Remove the package if present
#        update_cache: true  # Update cache before checking for git 

    - name: Download and run Azure CLI install script
      block:
        - name: Add the Azure CLI apt key
          ansible.builtin.apt_key:
            url: https://packages.microsoft.com/keys/microsoft.asc
            keyring:  /etc/apt/keyrings/microsoft.gpg
            #keyring:  /usr/share/keyrings/microsoft.gpg

#        - name: Get distribution codename
#          ansible.builtin.command:
#            cmd: lsb_release -cs
#          register: az_dist
#        
#        - name: Get architecture
#          ansible.builtin.command:
#            cmd: dpkg --print-architecture
#          register: az_arch
        
        - name: Add Azure CLI repository
          ansible.builtin.apt_repository:
            #repo: "deb [arch={{ az_arch.stdout }} signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ az_dist.stdout }} main"
            repo: >
              deb 
              [signed-by=/etc/apt/keyrings/microsoft.gpg] 
              https://packages.microsoft.com/repos/azure-cli/ 
              jammy
              main
            #state: present

    - name: Add the HashiCorp Repository and Install Terraform
      block:
        - name: Add the hashicorp apt key
          ansible.builtin.apt_key:
            url: https://apt.releases.hashicorp.com/gpg
            keyring:  /usr/share/keyrings/hashicorp-archive-keyring.gpg 
        
        # see https://www.vagrantup.com/downloads
        - name: Add the hashicorp repository
          ansible.builtin.apt_repository:
            repo: >
              deb
              [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]
              https://apt.releases.hashicorp.com
              {{ ansible_distribution_release }}
              main
    
        - name: Install Terraform
          apt:
            name: terraform
            state: latest
            update_cache: true      
      become: true   

    - name: Add the GitHub CLI Repository and Install GigHub CLI
      block:
        - name: Download and set up GitHub CLI GPG key
          ansible.builtin.apt_key:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

        - name: Add GitHub CLI repository
          ansible.builtin.apt_repository:
            repo: >
              deb 
              [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] 
              https://cli.github.com/packages 
              stable 
              main

        - name: Install GitHub CLI
          apt:
            name: gh
            state: latest
            update_cache: true
      become: true           

    # see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
    - name: Add the kubernetes apt repository key
      ansible.builtin.apt_key:
        # e.g. https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        #url: https://pkgs.k8s.io/core:/stable:/v{{ (k8s_client_kubectl_version | split('.'))[:2] | join('.') }}/deb/Release.key
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        keyring: /etc/apt/keyrings/pkgs.k8s.io.gpg
    
    # see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
    - name: Add the kubernetes repository
      ansible.builtin.apt_repository:
        # see https://wiki.debian.org/DebianRepository/Format
        # see https://pkgs.k8s.io/core:/stable:/v1.29/deb/InRelease
        # see https://pkgs.k8s.io/core:/stable:/v1.29/deb/Packages
        # e.g. https://pkgs.k8s.io/core:/stable:/v1.29/deb/
        repo: >
          deb
          [signed-by=/etc/apt/keyrings/pkgs.k8s.io.gpg]
          https://pkgs.k8s.io/core:/stable:/v1.30/deb/
          /
    
    # NB execute apt-cache madison kubectl to known the available versions.
    - name: Install kubectl
      block:
        - name: Install kubectl
          apt:
            name: kubectl
            state: latest
            update_cache: true
    
    - name: Install kubectl bash completion
      block:
        - name: Get kubectl bash completion
          ansible.builtin.command: kubectl completion bash
          register: bash_completion
          changed_when: false
        - name: Install kubectl bash completion
          ansible.builtin.copy:
            content: "{{ bash_completion.stdout }}"
            dest: /usr/share/bash-completion/completions/kubectl
            mode: 0444

    - name: Change shell to zsh
      ansible.builtin.user:
        name: "{{ remote_regular_user }}"
        shell: /usr/bin/zsh