---
- name: Ansible Config
  hosts: localhost
  connection: local
  vars_files:
    - ~/ansible/group_vars/vault.yml  # path to the vault file

  #vars:  # moved to all.yml
  #  new_user: joe
  #  new_user_password: new_user_password # moved to all.yml

  #roles:  # moved to all.yml
  #  - custom-roles
  #  - system

  pre_tasks:
    #- name:  Detect Host User
    #  ansible.builtin.import_tasks: pre_tasks/whoami.yml
    #  tags:
    #    always

    - name: Valiate host_user and ansible_user_dir
      debug:
        msg: "host_user is {{ host_user }}, ansible_user_dir is {{ ansible_user_dir }}"

  tasks:
    - name: Update apt and install required system packages
      apt:
        name:
          - tree
          - bat
          - fzf
        state: latest
        update_cache: true
      become: true  
      when: ansible_distribution in ["Debian", "Ubuntu"]  

    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always  