---
- hosts: all
  become: true
  gather_facts: true
  vars_files:
    - /home/jiadmin/ansible/group_vars/vault.yml  # path to the vault file
    #- ~/ansible/group_vars/vault.yml  # path to the vault file

  #vars:  # moved to all.yml
  #  new_user: joe
  #  new_user_password: new_user_password # moved to all.yml

  #roles:  # moved to all.yml
  #  - custom-roles
  #  - system

  pre_tasks:
    - name:  Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        always

  tasks:
#    - name: Install aptitude
#      apt:
#        name: aptitude
#        state: latest
#        update_cache: true 

    - name: Update apt and install required system packages
      apt:
        name:
          - python3-passlib
          - locales          
          - curl
          - neovim
          - unzip
          - git
          - wget
          - tree
          - zsh
        state: latest
        update_cache: true
      when: ansible_distribution in ["Debian", "Ubuntu"]  
       
    - name: Include multiple tasks
      include_tasks: "{{ item }}"
      loop:
        - roles/system/tasks/main.yml
        - roles/custom-roles/tasks/create_user.yml  
        - roles/custom-roles/tasks/fonts.yml
        - roles/custom-roles/tasks/zsh.yml
        - roles/custom-roles/tasks/starship.yml
        - roles/custom-roles/tasks/neofetch.yml
        - roles/custom-roles/tasks/azure_cli.yml
        - roles/custom-roles/tasks/terraform.yml
        - roles/custom-roles/tasks/github_cli.yml
        - roles/custom-roles/tasks/kubectl.yml
        