- name: Download and run Azure CLI install script
  block:
    - name: Add the Azure CLI apt key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring:  /etc/apt/keyrings/microsoft.gpg
    - name: Add Azure CLI repository
      ansible.builtin.apt_repository:
        #repo: "deb [arch={{ az_arch.stdout }} signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ az_dist.stdout }} main"
        repo: >
          deb 
          [signed-by=/etc/apt/keyrings/microsoft.gpg] 
          https://packages.microsoft.com/repos/azure-cli/ 
          jammy
          main
        state: present
    - name: Update apt and install Azure CLI
      ansible.builtin.apt:
        name: azure-cli
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"    