- name: Install and configure zsh
  block:
    - name: Install zsh
      apt:
        name: zsh
        state: latest
        update_cache: yes
    
    - name: Delete .zshrc file if it exists
      file:
        path: "/home/{{ host_user }}/.zshrc"
        state: absent

    - name: Create zsh directory /home/{{ host_user }}/.config/zsh/
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.config/zsh/"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0755  

    - name: Create plugins /home/{{ host_user }}/.config/zsh/plugins/
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.config/zsh/plugins/"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0755  

    - name: Install ZSH syntax highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ host_user }}/.config/zsh/plugins/zsh-syntax-highlighting"

    - name: Install ZSH autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "/home/{{ host_user }}/.config/zsh/plugins/zsh-autosuggestions"

    - name: Copy .zshenv file | /home/{{ host_user }}/.zshenv | 
      ansible.builtin.copy:
        src: .zshenv
        dest: "/home/{{ host_user }}/.zshenv"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0755"

    - name: Copy .zcompdump file | /home/{{ host_user }}/.config/zsh/.zcompdump  | 
      ansible.builtin.copy:
        src: .zcompdump 
        dest: "/home/{{ host_user }}/.config/zsh/.zcompdump"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0755"

    - name: Copy .zshrc file | /home/{{ host_user }}/.config/zsh/.zshrc  | 
      ansible.builtin.copy:
        src: .zshrc 
        dest: "/home/{{ host_user }}/.config/zsh/.zshrc"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0755"

    - name: Change shell to zsh
      ansible.builtin.user:
        #name: "{{ remote_regular_user }}"
        name: "/home/{{ host_user }}"
        shell: /usr/bin/zsh        
  become: true      
