- name: Install and configure zsh
  block:
    - name: Install zsh
      apt:
        name: zsh
        state: latest
        update_cache: yes
    
    - name: Delete .zshrc file if it exists
      file:
        path: "/home/{{ ansible_env['USER'] }}/.zshrc"
        state: absent

    - name: Create directory /home/{{ ansible_env['USER'] }}/.config/zsh/
      ansible.builtin.file:
        path: "/home/{{ ansible_env['USER'] }}/.config/zsh/"
        state: directory
        mode: 0755  

    - name: Download .zsh configuration file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zshrc
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/.zshrc"

    - name: Download zsh history file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zsh_history
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/.zshrc_history"

    - name: Download zsh zcompdump file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zcompdump
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/.zcompdump"

    - name: Create directory /home/{{ ansible_env['USER'] }}/.config/zsh/plugins/
      ansible.builtin.file:
        path: "/home/{{ ansible_env['USER'] }}/.config/zsh/plugins/"
        state: directory
        mode: 0755  

    - name: Install ZSH syntax highlighting and autosuggestions
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zshrc
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/.zshrc"

    - name: Install ZSH syntax highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ ansible_env['USER'] }}}/.config/zsh/plugins/zsh-syntax-highlighting"

    - name: Install ZSH autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/plugins/zsh-autosuggestions"

    - name: download the zsh-history-substring-search plugin to a custom plugin directory and install
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: "/home/{{ ansible_env['USER'] }}/.config/zsh/plugins/zsh-history-substring-search"   

    - name: Download .zshenv file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.zshenv
        dest: "/home/{{ ansible_env['USER'] }}/.zshenv"

###############################################################

    - name: Change shell to zsh
      ansible.builtin.user:
        #name: "{{ remote_regular_user }}"
        name: "/home/{{ ansible_env['USER'] }}"
        shell: /usr/bin/zsh
  become: true      
