- name: Install and configure zsh
  block:
    - name: Install zsh
      apt:
        name: zsh
        state: latest
        update_cache: yes
    
    - name: Delete .zshrc file if it exists
      file:
        path: "/home/{{ host_user }}/.zshrc"
        state: absent

    - name: Create directory /home/{{ host_user }}/.config/zsh/
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.config/zsh/"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0755  

#    - name: Download .zsh configuration file from GitHub
#      get_url:
#        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zshrc
#        dest: "/home/{{ host_user }}/.config/zsh/.zshrc"
#
#    - name: Download zsh history file from GitHub
#      get_url:
#        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zsh_history
#        dest: "/home/{{ host_user }}/.config/zsh/.zshrc_history"
#
#    - name: Download zsh zcompdump file from GitHub
#      get_url:
#        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zcompdump
#        dest: "/home/{{ host_user }}/.config/zsh/.zcompdump"

    - name: Create directory /home/{{ host_user }}/.config/zsh/plugins/
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.config/zsh/plugins/"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0755  

    - name: Install ZSH syntax highlighting and autosuggestions
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/zsh/.zshrc
        dest: "/home/{{ host_user }}/.config/zsh/.zshrc"

    - name: Install ZSH syntax highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "/home/{{ host_user }}/.config/zsh/plugins/zsh-syntax-highlighting"

    - name: Install ZSH autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "/home/{{ host_user }}/.config/zsh/plugins/zsh-autosuggestions"

    - name: download the zsh-history-substring-search plugin to a custom plugin directory and install
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: "/home/{{ host_user }}/.config/zsh/plugins/zsh-history-substring-search"   

    - name: Download .zshenv file from GitHub
      get_url:
        url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.zshenv
        dest: "/home/{{ host_user }}/.zshenv"

    - name: Change shell to zsh
      ansible.builtin.user:
        #name: "{{ remote_regular_user }}"
        name: "/home/{{ host_user }}"
        shell: /usr/bin/zsh

    - name: Copy .zshenv file | /home/{{ host_user }}/.zshenv | 
      ansible.builtin.copy:
        src: .zshenv
        dest: "/home/{{ host_user }}/.zshenv"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0644"

    - name: "Create symlink to the .zshenv file"
      ansible.builtin.file:
        src: "{{ role_path }}/files/.zshenv"
        dest: "/home/{{ host_user }}/.zshenv"
        state: link
        force: true   

    - name: Copy .zcompdump file | /home/{{ host_user }}/.zcompdump  | 
      ansible.builtin.copy:
        src: .zcompdump 
        dest: "/home/{{ host_user }}/.zcompdump"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0644"

    - name: "Create symlink to the .zcompdump file"
      ansible.builtin.file:
        src: "{{ role_path }}/files/.zcompdump"
        dest: "/home/{{ host_user }}/.zcompdump"
        state: link
        force: true 

    - name: Copy .zshrc file | /home/{{ host_user }}/.zshrc  | 
      ansible.builtin.copy:
        src: .zshrc 
        dest: "/home/{{ host_user }}/.zshrc"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0644"

    - name: "Create symlink to the .zshrc file"
      ansible.builtin.file:
        src: "{{ role_path }}/files/.zshrc"
        dest: "/home/{{ host_user }}/.zshrc"
        state: link
        force: true 

    - name: Copy .zshrc_history file | /home/{{ host_user }}/.zshrc_history  | 
      ansible.builtin.copy:
        src: .zshrc_history 
        dest: "/home/{{ host_user }}/.zshrc_history"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: "0644"

    - name: "Create symlink to the .zshrc_history file"
      ansible.builtin.file:
        src: "{{ role_path }}/files/.zshrc_history"
        dest: "/home/{{ host_user }}/.zshrc_history"
        state: link
        force: true 
  become: true      
