---
- name: "Tmux | {{ ansible_distribution }} | Install tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: tmux
    dest: "{{ ansible_user_dir }}/.config/"
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: "0755"

- name: Download single file from GitHub"
  get_url:
    url: https://raw.githubusercontent.com/guanz808/ansible/main/roles/tmux/files/tmux/tmux.conf
    dest: "/home/{{ host_user }}/.config/neofetch/config.conf"
