---
- name: Update apt and install required system packages
  apt:
    name:
      - python3-passlib
    state: latest
    update_cache: true
  when: ansible_distribution in ["Debian", "Ubuntu"]  

- name: Create a new regular user with sudo privileges
  ansible.builtin.user:
    name: "{{ new_user }}"
    password: "{{ new_user_password | password_hash }}"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present