---
- name: Install and configure Neofetch
  block:
    - name: Install neofetch
      apt:
        name: neofetch
        state: latest
        update_cache: true
      become: true  
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      
#    - name: Run program neofetch
#      command: /usr/bin/neofetch --arguments
#      become: true  # optional, depending on program requirements

    - name: Create directory | /home/{{ host_user }}/.config/neofetch/ |
      ansible.builtin.file:
        path: "/home/{{ host_user }}/.config/neofetch/"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0755  
   
    - name: Download single file from GitHub"
      get_url:
        url: https://raw.githubusercontent.com/guanz808/ansible/main/roles/neofetch/files/config.conf
        dest: "/home/{{ host_user }}/.config/neofetch/config.conf"

#    - name: Copy config file | /home/{{ host_user }}/.config/neofetch/config.conf | 
#      ansible.builtin.copy:
#        src: config.conf
#        dest: "/home/{{ host_user }}/.config/neofetch/config.conf"
#        owner: "{{ host_user }}"
#        group: "{{ host_user }}"
#        mode: "0644"

    - name: Edit bashrc"
      #become: true  # Retain this for clarity and consistency
      lineinfile:
        path: "/home/{{ host_user }}/.bashrc"
        #regexp: '^$'  # Match an empty line (end of file)
        insertafter: EOF  # Append the line after the last match (end of file)
        line: 'neofetch'  # Replace 'xxx' with the actual line you want to add
      #when: ansible_distribution == "Ubuntu"

    #- name: Edit zshrc"
    #  #become: true  # Retain this for clarity and consistency
    #  lineinfile:
    #    path: "/home/{{ host_user }}/.config/zsh/.zshrc"
    #    #regexp: '^$'  # Match an empty line (end of file)
    #    insertafter: EOF  # Append the line after the last match (end of file)
    #    line: 'neofetch'  # Replace 'xxx' with the actual line you want to add
    #  #when: ansible_distribution == "Ubuntu"      

    - name: Check for .zshrc file
      stat:
        path: "/home/{{ host_user }}/.config/zsh/.zshrc"
      register: zshrc_stat
    
    - name: Add neofetch to the .zshrc file (if it exists)
      become: true
      lineinfile:
        path: "/home/{{ host_user }}/.config/zsh/.zshrc"
        #regexp: '^$'  # Commented out (optional for specific insertion)
        insertafter: EOF
        line: 'neofetch'
      when: zshrc_stat.stat.exists  # Only run if file exists