---
- name: Update apt and install required system packages
  apt:
    name:
      - wget
    state: latest
    update_cache: true
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]  

#- name: Download and install Starship
#  get_url:
#    url: https://starship.rs/install.sh
#    dest: ~/starshipInstall.sh
#    mode: '0755'
#
#- name: Run the install script
#  command: ~/starshipInstall.sh -y
#  become: true

- name: Check if Starship is installed
  command: starship --version
  register: starship_version
  failed_when: false
  changed_when: false

- name: Download install.sh from starship.rs
  get_url:
    url: https://starship.rs/install.sh
    dest: "/home/{{ host_user }}/starshipInstall.sh"
    mode: '0755'
  when: starship_version.rc != 0

- name: Run the install script
  command: "/home/{{ host_user }}/starshipInstall.sh -y"
  when: starship_version.rc != 0
  become: true

- name: Create directory /home/{{ host_user }}/.config/starship/
  ansible.builtin.file:
    path: "/home/{{ host_user }}/.config/starship/"
    state: directory
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
    mode: 0755  

- name: Download .zsh configuration file from GitHub
  get_url:
    url: https://raw.githubusercontent.com/guanz808/dotfiles/main/.config/starship/starship.toml
    dest: "/home/{{ host_user }}/.config/starship/starship.toml" 

#- name: Check for zshrc file
#  stat:
#    path: "/home/{{ host_user }}/.config/zsh/.zshrc"
#  register: zshrc_stat
#
#- name: Edit zshrc (if it exists)
#  become: true
#  lineinfile:
#    path: "/home/{{ host_user }}/.config/zsh/.zshrc"
#    #regexp: '^$'  # Commented out (optional for specific insertion)
#    insertafter: EOF
#    line: 'eval "$(starship init zsh)"'
#  when: zshrc_stat.stat.exists  # Only run if file exists   